/**
 * This script exports the version of the SDK from the package.json to src/version.ts
 */

const fs = require('fs');
const path = require('path');

// Read the version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = require(packageJsonPath);
const version = packageJson.version;

// Create the output string
const comment = '// This file is generated by scripts/exportVersion.js\n';
const varStr = `export const SDK_VERSION = '${version}';\n`;
const output = comment + varStr;

// Write the output to src/version.ts
const outputPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(outputPath, output);
