/**
 * Interface representing a request to compose a message.
 */
export interface ComposeMessageRequest {
  /**
   * The prompt that smart compose will use to generate a message suggestion.
   */
  prompt: string;
}

/**
 * Interface representing a response to a message composition request.
 */
export interface ComposeMessageResponse {
  /**
   * The message suggestion generated by smart compose.
   */
  suggestion: string;
}
