name: Cloudflare Test Simple

on:
  push:
    branches:
      - cursor/add-cloudflare-worker-to-test-matrix-3aca
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-cloudflare:
    name: Test Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Wrangler CLI
        run: npm install -g wrangler@latest

      - name: Build the SDK
        run: npm run build

      - name: Test Cloudflare Workers compatibility
        run: |
          echo "🧪 Testing Cloudflare Workers compatibility..."
          npm run test:cloudflare