name: Test Workflow

on:
  push:
    branches:
      - cursor/add-cloudflare-worker-to-test-matrix-3aca
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-basic:
    name: Test Basic Functionality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the SDK
        run: npm run build

      - name: Run basic test
        run: |
          echo "✅ Basic workflow is working!"
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Current branch: $(git branch --show-current)"

      - name: Test Cloudflare Workers compatibility
        run: |
          echo "🧪 Testing Cloudflare Workers compatibility..."
          npm run test:cloudflare